# Generated by Django 4.2 on 2024-01-14 19:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('correct_answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTable',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255, unique=True)),
                ('score', models.IntegerField()),
                ('start_time', models.DateTimeField(default=datetime.datetime(2024, 1, 15, 1, 25, 43, 744875))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2024, 1, 15, 3, 25, 43, 744875))),
                ('attempts', models.IntegerField(default=2)),
                ('current_question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rc_app.question')),
            ],
        ),
    ]
